export const language = {
  english: {
    projects: "Projects",
    helloworld: "Hello World!",
    hireme: "Hire me",
    amI: "I'm a ",
    roles: "Web, UI/UX and Graphic Designer.",
    pleasure: "It will be a pleasure to make part of",
    your: "your",
    journey: "journey",
    myprojects: [
      { 1: "Mmy", 2: "Projectss" },
      { 1: "Mmy", 2: "Prrojjectts" },
      { 1: "My", 2: "Proojects" },
      { 1: "My", 2: "Pprojjeccts" },
      { 1: "Mmy", 2: "Projects" },
    ],
    lifeisgood: "life is good",
    untitled: "Untitled Project",
  },
  portuguese: {
    projects: "Projetos",
    helloworld: "Olá Mundo!",
    hireme: "Me contrate",
    amI: "Eu sou ",
    roles: "Designer Gráfico, UI/UX e Web.",
    pleasure: "Será um prazer fazer parte da sua",
    your: "sua",
    journey: "jornada",
    myprojects: [
      { 1: "Meeuss", 2: "Projeetoss" },
      { 1: "Meuus", 2: "Prrojjettos" },
      { 1: "MMeus", 2: "Proojeetos" },
      { 1: "Meeuss", 2: "Pprojjettos" },
      { 1: "Meus", 2: "Projetos" },
    ],
    lifeisgood: "a vida é boa",
    untitled: "Projeto sem título",
  },
};
