export const language = {
  english: {
    home: "Home",
    projects: "Projects",
    helloworld: "Hello World!",
    hireme: "Hire me",
    amI: "I am a",
    roles: "Web, UI/UX and Graphic Designer.",
    pleasure: "It will be a pleasure to be part of",
    your: "your",
    journey: "journey",
    myprojects: "My proojeects",
    lifeisgood: "life is good",
  },
  portuguese: {
    home: "Início",
    projects: "Projetos",
    helloworld: "Olá Mundo!",
    hireme: "Me contrate",
    amI: "Eu sou ",
    roles: "Web, UI/UX e Designer Gráfico.",
    pleasure: "Será um prazer ser parte da sua",
    your: "sua",
    journey: "jornada",
    myprojects: "Mmeuss proojeetos",
    lifeisgood: "a vida é boa",
  },
};
